/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Action, Input } from "adaptivecards";
export namespace Components {
    interface AdaptiveCard {
        "afterSubmit"?: (data) => void;
        "beforeSubmit"?: (data) => void;
        "data"?: string | object;
        "elementKey"?: string;
        "href"?: string;
        "mode": string;
        "submitTarget"?: string;
        "template"?: any;
        "templateId"?: any;
    }
}
declare global {
    interface HTMLAdaptiveCardElement extends Components.AdaptiveCard, HTMLStencilElement {
    }
    var HTMLAdaptiveCardElement: {
        prototype: HTMLAdaptiveCardElement;
        new (): HTMLAdaptiveCardElement;
    };
    interface HTMLElementTagNameMap {
        "adaptive-card": HTMLAdaptiveCardElement;
    }
}
declare namespace LocalJSX {
    interface AdaptiveCard {
        "afterSubmit"?: (data) => void;
        "beforeSubmit"?: (data) => void;
        "data"?: string | object;
        "elementKey"?: string;
        "href"?: string;
        "mode"?: string;
        "onCardAfterSubmit"?: (event: CustomEvent<Action>) => void;
        "onCardInputChanged"?: (event: CustomEvent<Input>) => void;
        "onCardSubmit"?: (event: CustomEvent<Action>) => void;
        "submitTarget"?: string;
        "template"?: any;
        "templateId"?: any;
    }
    interface IntrinsicElements {
        "adaptive-card": AdaptiveCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "adaptive-card": LocalJSX.AdaptiveCard & JSXBase.HTMLAttributes<HTMLAdaptiveCardElement>;
        }
    }
}
